image:
  name: atlassian/default-image:3

definitions:
  test: &test
    step:
      name: Test
      image: python:3.10
      script:
        - make setup lint test
      services:
        - docker


  snyk-scan: &snyk-scan
    step:
      name: Snyk scan
      image: python:3.10
      script:
        # build docker image artifact
        - export IMAGE_NAME=bitbucketpipelines/${BITBUCKET_REPO_SLUG}
        - export IMAGE_VERSION=pipelines-${BITBUCKET_BUILD_NUMBER}
        - docker build -t $IMAGE_NAME:$IMAGE_VERSION -t $IMAGE_NAME:latest .
        - docker save --output docker-image.tar.gz $IMAGE_NAME
        - pipe: snyk/snyk-scan:0.5.3
          variables:
            SNYK_TOKEN: $SNYK_TOKEN
            LANGUAGE: "docker"
            IMAGE_NAME: $IMAGE_NAME:$IMAGE_VERSION
            TARGET_FILE: "Dockerfile"
            SEVERITY_THRESHOLD: "high"
            DONT_BREAK_BUILD: "true"
            CODE_INSIGHTS_RESULTS: "true" # Optional - Generates a code insights report in pull request view
            MONITOR: "true"
            DEBUG: "true"
      services:
        - docker
      artifacts:
        - docker-image.tar.gz


  release-dev: &release-dev
    step:
      name: Release development version
      image: python:3.10
      trigger: manual
      script:
        - docker load --input docker-image.tar.gz
        - pip install semversioner
        - ./ci-scripts/docker-release-dev.sh bitbucketpipelines/${BITBUCKET_REPO_SLUG}
        - ./ci-scripts/git-release-dev.sh
      services:
      - docker


  push: &push
    step:
      name: Push and Tag
      image: python:3.10
      script:
        - docker load --input docker-image.tar.gz
        - pip install semversioner
        - ./ci-scripts/bump-version.sh
        - ./ci-scripts/docker-release.sh bitbucketpipelines/${BITBUCKET_REPO_SLUG}
        - ./ci-scripts/git-release.sh
      services:
      - docker


pipelines:
  default:
    - <<: *test
    - <<: *snyk-scan
    - <<: *release-dev
  branches:
    master:
      - <<: *test
      - <<: *snyk-scan
      - <<: *push
