apiVersion: v1
kind: ServiceAccount
metadata:
  name: runners-autoscaler
  namespace: bitbucket-runner-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runners-autoscaler
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runners-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runners-autoscaler
subjects:
  - kind: ServiceAccount
    name: runners-autoscaler
    namespace: bitbucket-runner-control-plane
