apiVersion: v1
kind: ConfigMap
metadata:
  name: runners-autoscaler-job-template
  namespace: bitbucket-runner-control-plane
data:
  job.yaml.template: |
    apiVersion: v1
    kind: List
    items:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: runner-oauth-credentials-<%runner_uuid%>  # mandatory, don't modify
          labels:
            account_uuid: <%account_uuid%>  # mandatory, don't modify
        {%- if repository_uuid %}
            repository_uuid: <%repository_uuid%>  # mandatory, don't modify
        {%- endif %}
            runner_uuid: <%runner_uuid%>  # mandatory, don't modify
            runner_namespace: <%runner_namespace%>  # mandatory, don't modify
        data:
          oauth_client_id: <%oauth_client_id_base64%>
          oauth_client_secret: <%oauth_client_secret_base64%>
      - apiVersion: batch/v1
        kind: Job
        metadata:
          name: runner-<%runner_uuid%>  # mandatory, don't modify
        spec:
          template:
            metadata:
              labels:
                customer: shared
                account_uuid: <%account_uuid%>  # mandatory, don't modify
                runner_uuid: <%runner_uuid%>  # mandatory, don't modify
            {%- if repository_uuid %}
                repository_uuid: <%repository_uuid%>  # mandatory, don't modify
            {%- endif %}
                runner_namespace: <%runner_namespace%>  # mandatory, don't modify
            spec:
              containers:
                - name: runner
                  image: docker-public.packages.atlassian.com/sox/atlassian/bitbucket-pipelines-runner:1  # This autoscaler needs the runner image to run, you can use the latest or pin any version you want.
                  imagePullPolicy: Always
                  resources:  # This is memory and cpu resources section that you can configure via config map settings file.
                    requests:
                      memory: "<%requests_memory%>"  # mandatory, don't modify
                      cpu: "<%requests_cpu%>"  # mandatory, don't modify
                    limits:
                      memory: "<%limits_memory%>"  # mandatory, don't modify
                      cpu: "<%limits_cpu%>"  # mandatory, don't modify
                  env:
                    - name: ACCOUNT_UUID  # mandatory, don't modify
                      value: "{<%account_uuid%>}"  # mandatory, don't modify
                {%- if repository_uuid %}
                    - name: REPOSITORY_UUID  # mandatory, don't modify
                      value: "{<%repository_uuid%>}"  # mandatory, don't modify
                {%- endif %}
                    - name: RUNNER_UUID  # mandatory, don't modify
                      value: "{<%runner_uuid%>}"  # mandatory, don't modify
                    - name: OAUTH_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                          name: runner-oauth-credentials-<%runner_uuid%>
                          key: oauth_client_id
                    - name: OAUTH_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: runner-oauth-credentials-<%runner_uuid%>
                          key: oauth_client_secret
                    - name: WORKING_DIRECTORY
                      value: "/tmp"
                  volumeMounts:
                    - name: tmp
                      mountPath: /tmp
                    - name: docker-containers
                      mountPath: /var/lib/docker/containers
                      readOnly: true
                    - name: var-run
                      mountPath: /var/run
                - name: docker
                  image: docker:dind
                  securityContext:
                    privileged: true
                  volumeMounts:
                    - name: tmp
                      mountPath: /tmp
                    - name: docker-containers
                      mountPath: /var/lib/docker/containers
                    - name: var-run
                      mountPath: /var/run
              restartPolicy: OnFailure
              volumes:
                - name: tmp
                - name: docker-containers
                - name: var-run
              nodeSelector:
                customer: shared
          backoffLimit: 6
          completions: 1
          parallelism: 1