apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-controller
  namespace: bitbucket-runner-control-plane
  labels:
    app: runner-controller
spec:
  selector:
    matchLabels:
      app: runner-controller
  template:
    metadata:
      name: runner-controller-pod
      labels:
        app: runner-controller
    spec:
      serviceAccountName: runners-autoscaler
      containers:
      - name: runner-controller
        image: bitbucketpipelines/runners-autoscaler:2.1.0
        volumeMounts:
        - name: runners-autoscaler-config
          mountPath: /opt/conf/config
          readOnly: true
        - name: runners-autoscaler-job-template
          mountPath: /opt/conf/job_template
          readOnly: true
        env:
          - name: BITBUCKET_USERNAME
            value: <BITBUCKET_USERNAME>
          - name: BITBUCKET_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: runner-bitbucket-credentials
                key: bitbucketClientSecret
        imagePullPolicy: IfNotPresent
      volumes:
        - name: runners-autoscaler-config
          configMap:
            name: runners-autoscaler-config
            defaultMode: 0644
            items:
              - key: runners_config.yaml
                path: runners_config.yaml
        - name: runners-autoscaler-job-template
          configMap:
            name: runners-autoscaler-job-template
            defaultMode: 0644
            items:
              - key: job.yaml.template
                path: job.yaml.template
