apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-controller-cleaner
  namespace: bitbucket-runner-control-plane
  labels:
    app: runner-controller-cleaner
spec:
  selector:
    matchLabels:
      app: runner-controller-cleaner
  template:
    metadata:
      name: runner-controller-cleaner-pod
      labels:
        app: runner-controller-cleaner
    spec:
      serviceAccountName: runners-autoscaler
      containers:
      - name: runner-controller-cleaner
        image: bitbucketpipelines/runners-autoscaler:1.6.2.166-dev
        command: ["python"]
        args: ["autoscaler/cleaner.py"]
        env:
          - name: BITBUCKET_USERNAME
            value: <BITBUCKET_USERNAME>
          - name: BITBUCKET_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: runner-bitbucket-credentials
                key: bitbucketClientSecret
        volumeMounts:
        - name: runners-autoscaler-config
          mountPath: /opt/conf/config
          readOnly: true
        imagePullPolicy: IfNotPresent
      volumes:
        - name: runners-autoscaler-config
          configMap:
            name: runners-autoscaler-config
            defaultMode: 0644
            items:
              - key: runners_config.yaml
                path: runners_config.yaml
