apiVersion: v1
kind: Secret
metadata:
  name: runner-bitbucket-credentials
  namespace: bitbucket-runner-control-plane
data:
  ###
  # Choose one of the options:
  # Basic auth BITBUCKET_APP_PASSWORD
  bitbucketClientSecret: <BITBUCKET_APP_PASSWORD base64>
  # or OAUTH auth BITBUCKET_OAUTH_CLIENT_ID and BITBUCKET_OAUTH_CLIENT_SECRET
  bitbucketOauthClientId: <BITBUCKET_OAUTH_CLIENT_ID base64>
  bitbucketOauthClientSecret: <BITBUCKET_OAUTH_CLIENT_SECRET base64>